### PR TITLE
feat: #55 User configuration for relay controls

### PR DESCRIPTION
**Pull request by xurizaemon**
Works, input welcome!

## In this PR

- [x] UI for configuring behaviour
- [x] Pre-populate new form fields
- [x] Storage of relay preference
- [x] Adjust query / filter relayed posts
- [ ] Move storage to UserSettings https://github.com/thilobillerbeck/skymoth/pull/57#issuecomment-2539722437

## Data / schema changes

- Adds `relayCriteria` (all, favedBySelf, containsMarker, notContainsMarker) and `relayMarker` (string) to User
- Adds a `Constraint` class to pass to `getNewToots()`

## UI changes

Below "Bluesky App Password" input on root (`/`) form:

image

### CODE REVIEW

**Comment by thilobillerbeck** [comment]
Thanks for picking up work on this <3

How do you feel about splitting this up into a settings object (or use this existing one?). I don't know how much we want to pump up the main user object. (I have to clean up the settings object anyway at some point :D )

**Comment by xurizaemon** [comment]
@thilobillerbeck I did try using the UserSettings object, but had no luck making that work, so I've prototyped with storage directly on the User schema (for now, anyway).

For my testing, this is working OK so far! Will road test it myself over the xmas/NY break, happy to hear any input or testing feedback folks have.

**Review by thilobillerbeck — APPROVED** [review]
Tested and it works, thanks for contributing <3

**Pull request merged**
